-- ورشة السيارات: مخطط قاعدة البيانات وسياسات الوصول.
-- شغّل هذا الملف مرة واحدة من Supabase Dashboard > SQL Editor.
-- يعيد تشغيله إنشاء/تحديث سياسات الجداول الخمسة التي يديرها هذا التطبيق.
begin;

create table if not exists public.services (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name_ar text not null check (char_length(btrim(name_ar)) between 2 and 120),
  description_ar text not null default '',
  duration_minutes integer not null default 60 check (duration_minutes between 15 and 480),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null check (char_length(btrim(full_name)) between 2 and 120),
  phone text not null unique check (phone ~ '^[+]9665[0-9]{8}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cars (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete restrict,
  make text not null check (char_length(btrim(make)) between 1 and 100),
  model text not null check (char_length(btrim(model)) between 1 and 100),
  plate_number text,
  created_at timestamptz not null default now(),
  constraint cars_customer_plate_unique unique (customer_id, plate_number),
  constraint cars_plate_length check (plate_number is null or char_length(plate_number) <= 32)
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  reference_code text not null unique check (reference_code ~ '^WR-[0-9A-F]{12}$'),
  customer_id uuid not null references public.customers(id) on delete restrict,
  car_id uuid not null references public.cars(id) on delete restrict,
  service_id integer not null references public.services(id) on delete restrict,
  appointment_at timestamptz not null,
  duration_minutes integer not null check (duration_minutes between 15 and 480),
  status text not null default 'new' check (status in ('new','confirmed','completed','cancelled')),
  notes text not null default '' check (char_length(notes) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bookings_active_appointment_idx
  on public.bookings (appointment_at)
  where status in ('new','confirmed');
create index if not exists bookings_customer_recent_idx
  on public.bookings (customer_id, created_at desc);
create index if not exists bookings_car_idx on public.bookings (car_id);
create index if not exists bookings_service_status_idx
  on public.bookings (service_id, status);
create index if not exists services_active_name_idx
  on public.services (active, name_ar);

insert into public.services (slug, name_ar, description_ar, duration_minutes, active)
values
  ('periodic-maintenance', 'صيانة دورية', 'فحص وصيانة دورية لأهم أنظمة السيارة.', 60, true),
  ('oil-change', 'تغيير زيت المحرك', 'تغيير الزيت وفحص مستوى السوائل.', 30, true),
  ('comprehensive-inspection', 'فحص شامل', 'فحص عام للمحرك والفرامل والإطارات والأنظمة الأساسية.', 60, true),
  ('ac-service', 'صيانة المكيف', 'فحص نظام التكييف وكفاءة التبريد.', 45, true)
on conflict (slug) do nothing;

-- إنشاء ملف افتراضي لكل مستخدم Auth جديد؛ بيانات metadata لا تمنح دور admin.
create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
  insert into public.profiles (id, role)
  values (new.id, 'customer')
  on conflict (id) do nothing;
  return new;
end;
$function$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

-- يشمل المستخدمين الذين كانوا موجودين قبل تشغيل هذا الملف.
insert into public.profiles (id, role)
select u.id, 'customer'
from auth.users as u
on conflict (id) do nothing;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $function$
  select exists (
    select 1
    from public.profiles as p
    where p.id = (select auth.uid())
      and p.role = 'admin'
  );
$function$;

revoke all on function public.is_admin() from public, anon;
revoke all on function public.handle_new_user_profile() from public, anon, authenticated;
grant execute on function public.is_admin() to authenticated;

create or replace function public.guard_booking_status_transition()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'new' and new.status in ('confirmed','cancelled'))
      or (old.status = 'confirmed' and new.status in ('completed','cancelled'))
    ) then
      raise exception using
        errcode = '22023',
        message = 'This booking status transition is not allowed';
    end if;
    new.updated_at := now();
  end if;
  return new;
end;
$function$;

revoke all on function public.guard_booking_status_transition() from public, anon, authenticated;
drop trigger if exists bookings_status_transition_guard on public.bookings;
create trigger bookings_status_transition_guard
before update of status on public.bookings
for each row execute function public.guard_booking_status_transition();

-- RPC آمن: الزائر لا يحصل على صلاحيات INSERT/SELECT مباشرة.
-- القفل داخل transaction يجعل فحص تداخل المواعيد آمنًا عند الطلبات المتزامنة.
drop function if exists public.create_public_booking(text,text,text,text,text,integer,timestamptz,text);

create function public.create_public_booking(
  p_full_name text,
  p_phone text,
  p_car_make text,
  p_car_model text,
  p_plate_number text,
  p_service_id integer,
  p_appointment_at timestamptz,
  p_notes text default null
)
returns table (
  reference_code text,
  appointment_at timestamptz,
  full_name text,
  car_make text,
  car_model text,
  service_name_ar text
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_full_name text := nullif(btrim(coalesce(p_full_name, '')), '');
  v_phone_input text;
  v_phone text;
  v_car_make text := nullif(btrim(coalesce(p_car_make, '')), '');
  v_car_model text := nullif(btrim(coalesce(p_car_model, '')), '');
  v_plate_number text := nullif(btrim(coalesce(p_plate_number, '')), '');
  v_notes text := btrim(coalesce(p_notes, ''));
  v_appointment_at timestamptz := p_appointment_at;
  v_new_end timestamptz;
  v_service public.services%rowtype;
  v_customer_id uuid;
  v_car_id uuid;
  v_reference_code text;
  v_booked_at timestamptz;
begin
  if v_full_name is null or char_length(v_full_name) not between 2 and 120 then
    raise exception using errcode = '22023', message = 'Invalid customer name';
  end if;

  v_phone_input := regexp_replace(
    translate(
      btrim(coalesce(p_phone, '')),
      '٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹',
      '01234567890123456789'
    ),
    '[[:space:]()-]',
    '',
    'g'
  );

  if v_phone_input ~ '^05[0-9]{8}$' then
    v_phone := '+966' || substr(v_phone_input, 2);
  elsif v_phone_input ~ '^9665[0-9]{8}$' then
    v_phone := '+' || v_phone_input;
  elsif v_phone_input ~ '^[+]9665[0-9]{8}$' then
    v_phone := v_phone_input;
  else
    raise exception using errcode = '22023', message = 'Invalid Saudi mobile number';
  end if;

  if v_car_make is null or char_length(v_car_make) > 100
     or v_car_model is null or char_length(v_car_model) > 100 then
    raise exception using errcode = '22023', message = 'Invalid car details';
  end if;
  if v_plate_number is not null and char_length(v_plate_number) > 32 then
    raise exception using errcode = '22023', message = 'Invalid plate number';
  end if;
  if char_length(v_notes) > 2000 then
    raise exception using errcode = '22023', message = 'Notes are too long';
  end if;
  if v_appointment_at is null or v_appointment_at <= now() then
    raise exception using errcode = '22023', message = 'Appointment must be in the future';
  end if;

  select s.*
  into v_service
  from public.services as s
  where s.id = p_service_id
    and s.active = true;

  if not found then
    raise exception using errcode = '22023', message = 'Service is unavailable';
  end if;

  v_new_end := v_appointment_at + make_interval(mins => v_service.duration_minutes);

  perform pg_advisory_xact_lock(71203100, 1);

  if exists (
    select 1
    from public.bookings as b
    where b.status in ('new','confirmed')
      and b.appointment_at >= v_appointment_at - interval '8 hours'
      and b.appointment_at < v_new_end
      and b.appointment_at + make_interval(mins => b.duration_minutes) > v_appointment_at
  ) then
    raise exception using errcode = '23P01', message = 'Appointment overlaps an existing booking';
  end if;

  insert into public.customers (full_name, phone)
  values (v_full_name, v_phone)
  on conflict (phone) do update
    set full_name = excluded.full_name,
        updated_at = now()
  returning id into v_customer_id;

  insert into public.cars (customer_id, make, model, plate_number)
  values (v_customer_id, v_car_make, v_car_model, v_plate_number)
  on conflict (customer_id, plate_number) do update
    set make = excluded.make,
        model = excluded.model
  returning id into v_car_id;

  v_reference_code := 'WR-' ||
    upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12));

  insert into public.bookings as created_booking (
    reference_code, customer_id, car_id, service_id,
    appointment_at, duration_minutes, status, notes
  )
  values (
    v_reference_code, v_customer_id, v_car_id, v_service.id,
    v_appointment_at, v_service.duration_minutes, 'new', v_notes
  )
  returning created_booking.reference_code, created_booking.appointment_at
  into v_reference_code, v_booked_at;

  reference_code := v_reference_code;
  appointment_at := v_booked_at;
  full_name := v_full_name;
  car_make := v_car_make;
  car_model := v_car_model;
  service_name_ar := v_service.name_ar;
  return next;
end;
$function$;

revoke all on function public.create_public_booking(text,text,text,text,text,integer,timestamptz,text)
  from public, anon, authenticated;
grant execute on function public.create_public_booking(text,text,text,text,text,integer,timestamptz,text)
  to anon, authenticated;

-- أزل أي سياسة سابقة عن هذه الجداول كي لا تتسع الصلاحية بمزيج OR في RLS.
do $block$
declare
  v_policy record;
begin
  for v_policy in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('services','customers','cars','bookings','profiles')
  loop
    execute format(
      'drop policy %I on %I.%I',
      v_policy.policyname,
      v_policy.schemaname,
      v_policy.tablename
    );
  end loop;
end;
$block$;

alter table public.services enable row level security;
alter table public.customers enable row level security;
alter table public.cars enable row level security;
alter table public.bookings enable row level security;
alter table public.profiles enable row level security;

create policy services_read_active_anon
  on public.services for select to anon
  using (active = true);
create policy services_read_active_or_admin
  on public.services for select to authenticated
  using (active = true or (select public.is_admin()));

create policy customers_admin_read
  on public.customers for select to authenticated
  using ((select public.is_admin()));
create policy cars_admin_read
  on public.cars for select to authenticated
  using ((select public.is_admin()));
create policy bookings_admin_read
  on public.bookings for select to authenticated
  using ((select public.is_admin()));
create policy bookings_admin_update
  on public.bookings for update to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

-- لا تستدعِ is_admin() من سياسة profiles؛ الدالة نفسها تقرأ profiles.
-- المستخدم يحتاج قراءة صفه فقط، بينما تتحقق الدالة بصلاحية SECURITY DEFINER.
create policy profiles_read_self
  on public.profiles for select to authenticated
  using (id = (select auth.uid()));

-- صلاحيات API صريحة؛ لا توجد كتابة عامة للجداول الحساسة.
grant usage on schema public to anon, authenticated;
revoke all on table public.services from public, anon, authenticated;
revoke all on table public.customers from public, anon, authenticated;
revoke all on table public.cars from public, anon, authenticated;
revoke all on table public.bookings from public, anon, authenticated;
revoke all on table public.profiles from public, anon, authenticated;

grant select on table public.services to anon, authenticated;
grant select on table public.customers, public.cars, public.bookings, public.profiles to authenticated;
grant update (status) on table public.bookings to authenticated;

commit;

